version: '2'
services:
  logstash-conf:
    image: logstash-conf:5.0
    environment:
      DOCKER_API_VERSION: '1.24'
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    volumes:
    - /etc/hostname:/etc/hostname
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/logstash:/logstash
    labels:
      io.rancher.sidekicks: logstash
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  logstash:
    image: logstash:5.5.2
    network_mode: container:logstash-conf
    volumes:
    - /data/docker:/docker
    - /var/log:/host/var/log
    volumes_from:
    - logstash-conf
    command:
    - bash
    - -c
    - logstash -f /tmp/conf.d -r